### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by L134139** [oldweipro/claude-to-chatgpt#10]
![001](https://github.com/oldweipro/claude-to-chatgpt/assets/51356527/77fb50f9-37f2-4aaa-8792-25d4575dec13)
![002](https://github.com/oldweipro/claude-to-chatgpt/assets/51356527/b3d1dc5d-08ae-4e4b-9af8-28179c181f15)

**Comment by oldweipro** [comment]
请检查 `sessionKeys` 设置是否正确，注意 `yaml` 中的数组格式:
```yaml
base-url:
claude:
  session-keys:
    - sk-aaa
    - sk-bbb
    - sk-ccc
http-proxy:

```
